chunk_size: 256
local_cpu: true
max_local_cpu_size: 64.0
remote_url: "mooncakestore://127.0.0.1:50051"
remote_serde: "naive"
store_location: "RemoteBackend"
retrieve_locations: ["RemoteBackend"]
extra_config:
  save_chunk_meta: false
  local_hostname: "127.0.0.1"
  metadata_server: "P2PHANDSHAKE"
  master_server_address: "127.0.0.1:50051"
  protocol: "rdma"
  device_name: "mlx5_105"
  global_segment_size: 68719476736
  local_buffer_size: 2147483648
